CREATE TABLE USER (id INT(10) AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL);
  

CREATE TABLE ROLE (id INT(10) AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL);
  
CREATE TABLE USER_ROLE (USER_id INT(10),ROLE_id INT(10));