INSERT INTO USER (ID, EMAIL, NAME, PASSWORD) VALUES (1,'michael@rnp.br', 'Michael Jackson','$2a$10$Gt1FmyaBBAJM53XJP1e8hODK8tGLy.qmFp5Q2QLOXOwBUAk0qFnE6');
INSERT INTO USER (ID, EMAIL, NAME, PASSWORD) VALUES (2,'Alan@rnp.br', 'Alan Conceição','$2a$10$Gt1FmyaBBAJM53XJP1e8hODK8tGLy.qmFp5Q2QLOXOwBUAk0qFnE6');
INSERT INTO USER (ID, EMAIL, NAME, PASSWORD) VALUES (3,'Andre@rnp.br', 'Andre Farias','$2a$10$Gt1FmyaBBAJM53XJP1e8hODK8tGLy.qmFp5Q2QLOXOwBUAk0qFnE6');

INSERT INTO ROLE (ID,NAME) VALUES (1,'ROLE_ADMIN');
INSERT INTO ROLE (ID,NAME) VALUES (2,'ROLE_USER');        

INSERT INTO USER_ROLE(USER_ID,ROLE_ID) VALUES (1,1);
INSERT INTO USER_ROLE(USER_ID,ROLE_ID) VALUES (2,2);
INSERT INTO USER_ROLE(USER_ID,ROLE_ID) VALUES (3,2);
INSERT INTO USER_ROLE(USER_ID,ROLE_ID) VALUES (3,1);
