CREATE TABLE `DIARY` (`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `DATE` DATE NOT NULL, `USER_ID` INT NOT NULL);
CREATE TABLE `APPOINTMENT` (`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, `TIME` TIME NOT NULL, `DESCRIPTION` VARCHAR(30) NOT NULL, `DIARY_ID` INT NOT NULL);

