INSERT INTO DIARY (DATE, USER_ID) VALUES ('2021-01-01',1);
INSERT INTO APPOINTMENT (DESCRIPTION,TIME,DIARY_ID) VALUES ('Segunda de manhã','09:30','1');
INSERT INTO APPOINTMENT (DESCRIPTION,TIME,DIARY_ID) VALUES ('Segunda de almoço','12:30','1');
INSERT INTO APPOINTMENT (DESCRIPTION,TIME,DIARY_ID) VALUES ('Segunda de tarde','14:30','1');

INSERT INTO DIARY (DATE, USER_ID) VALUES ('2021-01-02',2);
INSERT INTO APPOINTMENT (DESCRIPTION,TIME,DIARY_ID) VALUES ('Terça de manhã','09:30','2');
INSERT INTO APPOINTMENT (DESCRIPTION,TIME,DIARY_ID) VALUES ('Terça de almoço','12:30','2');
INSERT INTO APPOINTMENT (DESCRIPTION,TIME,DIARY_ID) VALUES ('Terça de tarde','14:30','2');

INSERT INTO DIARY (DATE, USER_ID) VALUES ('2021-01-02',3);
INSERT INTO APPOINTMENT (DESCRIPTION,TIME,DIARY_ID) VALUES ('Quarta de manhã','09:30','3');
INSERT INTO APPOINTMENT (DESCRIPTION,TIME,DIARY_ID) VALUES ('Quarta de almoço','12:30','3');
INSERT INTO APPOINTMENT (DESCRIPTION,TIME,DIARY_ID) VALUES ('Quarta de tarde','14:30','3');